name: uber_food
description: Mobile application for finding restaurants in your area.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  built_value: ^8.1.4
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_redux: ^0.8.2
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  google_fonts: ^2.2.0
  google_maps_flutter: ^2.1.1
  google_sign_in: ^5.2.3
  location: ^4.3.0
  password_strength: ^0.2.0
  place_picker: ^0.9.19
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  shimmer: ^2.0.0
  timeago: ^3.2.1

dev_dependencies:
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - res/

