name: uber_food
description: Mobile application for finding restaurants in your area.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  algolia: ^1.0.4
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  password_strength: ^0.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.3
  location: ^4.3.0
  google_maps_flutter: ^2.1.1
  font_awesome_flutter: ^9.2.0
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.0
  timeago: ^3.2.1
  bottom_navy_bar: ^6.0.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  built_value: ^8.1.4
  built_collection: ^5.1.1
  redux_epics: ^0.15.1
  rxdart: ^0.27.3

dev_dependencies:
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/

